
plugins {
    id 'com.gradleup.shadow' version '8.3.3'
    id 'java'
}

description = 'interceptors'

repositories {
    mavenCentral()
    gradlePluginPortal()
}

dependencies {
    compileOnly('com.datadoghq:dd-trace-api:1.39.0')
}

jar {
  manifest {
    attributes(
      "Premain-Class": "com.gregor.datadog.interceptors.InterceptorBootstrap"
    )
  }
}

/*
jar {
    manifest {
        attributes (
            "Premain-Class" : "com.gregor.datadog.interceptors.InterceptorBootstrap"
        )
    }
}

 */

tasks.named('shadowJar', com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar) {
    enableRelocation true
    archiveClassifier.set('')
}

assemble.dependsOn shadowJar
